New Sticker Pack, all animated
signalstickers/signalstickers pull request #351
Opened 2020-12-01 22:30 UTC by teynav

2020-12-01 22:38 UTC, romainricard requested changes

2020-12-01 22:38 UTC, romainricard commented on stickers.yml
> +
Remove this line

2020-12-01 22:38 UTC, romainricard commented on stickers.yml
> +  a92ed43943b90b6bed0f014a3d0a987d:
Can you fix the indentation for this pack and all the following?

2020-12-01 22:38 UTC, romainricard commented
Thanks for all these submissions! Please fix the error above and we'll be good to go! :+1:

2020-12-01 22:40 UTC, teynav reviewed
Sorry, it's my first time using github

2020-12-01 23:12 UTC, teynav commented
I did both of the thing you requested, what am I doing wrong here?

2020-12-02 20:38 UTC, romainricard commented
Thanks, the format is now correct!
There are some issues about some packs tho:

# Missing frames
Some stickers (in packs [8335949df80c37eb06c7c7872a75af68](https://signalstickers.com/pack/8335949df80c37eb06c7c7872a75af68?key=f67bd792a3a1ac00be64b6b6d21274c1e50ffbd66a52504345c1139cf8ad8a78), [293f5ffc19efa5ec5e777c5de95929d2](https://signalstickers.com/pack/293f5ffc19efa5ec5e777c5de95929d2?key=ea0f54e119172bddd959469f4d725c9ee37a43edfc310c49a28067de656bc800)) have missing frames, and thus stickers become invisible for some time, for example:

![image](https://user-images.githubusercontent.com/7778898/100921377-c5bed700-34dc-11eb-8133-a33eb353813a.png)

# Errors in layers

Some stickers (in [8335949df80c37eb06c7c7872a75af68](https://signalstickers.com/pack/8335949df80c37eb06c7c7872a75af68?key=f67bd792a3a1ac00be64b6b6d21274c1e50ffbd66a52504345c1139cf8ad8a78), [4d14ed77727bb3a53f379064c12a3ec5](https://signalstickers.com/pack/4d14ed77727bb3a53f379064c12a3ec5?key=a69794346f71ecfc533a4c86efda25167e433547a48f40112e091b48874e0a60), [82bbb0e722f3cfbfa73c981567c8f52b](https://signalstickers.com/pack/82bbb0e722f3cfbfa73c981567c8f52b?key=ff01047867757bebef2d6b3eea0cdca5da294013dc38433bf6d4e65064e11d24), [293f5ffc19efa5ec5e777c5de95929d2](https://signalstickers.com/pack/293f5ffc19efa5ec5e777c5de95929d2?key=ea0f54e119172bddd959469f4d725c9ee37a43edfc310c49a28067de656bc800)) 
have issues with layers transparency. Probably a problem of transparency.

![image](https://user-images.githubusercontent.com/7778898/100921387-cbb4b800-34dc-11eb-8e0e-4c430f6b4b26.png)
![image](https://user-images.githubusercontent.com/7778898/100922093-be4bfd80-34dd-11eb-924a-4e6a70d7beab.png)
![image](https://user-images.githubusercontent.com/7778898/100926547-e9395000-34e3-11eb-8e57-335fa641e784.png)
![image](https://user-images.githubusercontent.com/7778898/100926618-0837e200-34e4-11eb-87a9-18977c23f236.png)


I encourage you to take a little bit more time on your script to address these issues :smiley: 

These packs are good, and have been merged in https://github.com/signalstickers/signalstickers/commit/3f3fed51c5a1639ecee6bde5c7f0193cb3ddeddf.
https://signalstickers.com/pack/0876b357a5a8b06a192506aee2f2e09e?key=e6fa8c3db15d29c3a42e78e2f246bfedb39c8bf0034b067fd6bf5c2289f3e6b1
https://signalstickers.com/pack/249818aaf61019027e67397e6af41c4f?key=1f42ecfc4162e5b90a176911967ce6aa30e00d996b6babe72b2172122df25e02

2020-12-02 20:51 UTC, teynav commented
Okay , this was created with older script, i will rerun it with newer one!!! Older had issues like these, although i tried to delete older packs some might have creeped in , i am converting other sticker packs rn, will convert this too!!

2020-12-02 21:42 UTC, closed without merging