feat: add Report
signalstickers/signalstickers pull request #919
Opened 2024-03-06 21:33 UTC by MahavishnuT

Hi 👋 

# OVERVIEW

I added the report page for your website. This permits a user to report a sticker pack if found offensive or contrary to the rules.

+ Uses the API route `/report/`
+ Opens a new page, not a pop-up for the report itself

2024-03-06 22:15 UTC, romainricard requested changes
Looks good, thanks for the feature!
Two points are missing:
- Install eslint in your IDE and fix the formating (including whitespaces added by your linter)
- Fix the review comments :pray:

2024-03-06 22:15 UTC, romainricard commented on src/components/report/Report.tsx
> +                {/* [Control] Submit and Reset */}
Remove `and Reset`

2024-03-06 22:15 UTC, romainricard commented on src/components/report/Report.tsx
> +            quibusdam veniam voluptatem dolor?
Use the following text:

```
<p>Use this form to report a pack to Signalstickers' admins.</p>
<p>Please add context and explain why you are reporting this pack.</p>
```

2024-03-06 22:18 UTC, MahavishnuT commented on src/components/report/Report.tsx
> +            quibusdam veniam voluptatem dolor?
👍

2024-03-08 20:56 UTC, romainricard requested changes

2024-03-08 20:56 UTC, romainricard commented on src/components/report/Report.tsx
> +  const [stickerPackError, setStickerPackError] = React.useState('');
This has become useless, please remove

2024-03-08 20:56 UTC, romainricard commented on src/components/layout/AppLayout.tsx
Still some formating problems (spaces at the beginning of lines)

2024-03-08 20:56 UTC, romainricard commented on src/components/pack/StickerPackDetail.tsx
Still some formating problems (spaces at the beginning of lines)

2024-03-09 16:10 UTC, romainricard approved these changes

2024-03-09 16:10 UTC, merged

2024-03-09 16:10 UTC, romainricard commented
Thanks a lot @MahavishnuT! :sparkles: